title: "Evolución de Enfermedades de Transmisión por Mosquitos en La"
description: ""
author: "Juan Moisés de la Serna Tuya"
url: "https://juanmoisesd.github.io"
baseurl: "/evolucion-de-enfermedades-de-transmision-por-mosquitos-en-latinoamerica-2015-202"
